services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.react-app
    # command: npm start 
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
      - node_modules:/usr/src/app/node_modules 
    container_name: fso-course-part-2c-frontend

  json-server:
    build:   
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - 3001:3001
    volumes:
      - ./db.json:/usr/src/app/db.json  
    container_name: fso-course-part-2c-backend
volumes:
  node_modules:  