services:
  courseinfo:
    build: .
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
      - node_modules:/usr/src/app/node_modules
    container_name: courseinfo-container

volumes:
  node_modules: