version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    container_name: thephonebook-frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./backend/package.json:/app/package.json
      - ./backend/index.js:/app/index.js
    container_name: thephonebook-backend
