services:
  unicafe:
    build: .
    command: npm start 
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app/
      # - node_modules:/usr/src/app/node_modules 
    container_name: unicafe-container 

# volumes:
#   node_modules:  