version: '3.5'

services:
  unicafe:
    build: .
    command: npm start 
    ports:
      - 3000:3000
    # volumes:
      # - .:/app/
      # - /app/node_modules 
    container_name: unicafe-container 

# volumes:
#   node_modules:  