services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.react-app
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    container_name: thephonebook-frontend

  json-server:
    build:   
      context: .
      dockerfile: Dockerfile.json-server
    ports:
      - 3001:3001
    volumes:
      - ./db.json:/app/db.json  
    container_name: thephonebook-backend
